name: kinc_importemx
description: Imports a gene expression matrix into the binary format used by KINC.

keywords:
  - coexpression
  - networks
  - correlation
tools:
  - interproscan:
    description: The Knowledge Independent Network Construction (KINC) software is an application for constructing Gene Co-expression Networks (GCN) from gene expression data.
    homepage: https://kinc.readthedocs.io/en/latest/
    documentation: https://kinc.readthedocs.io/en/latest/
    tool_dev_url: https://github.com/SystemsGenetics/KINC
    doi: "doi.org/10.1093/bib/bbab495"
    licence: ['MIT']

input:
  - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
  - data:
        type: file
        description: The data matrix in tab-delimeted format.
        pattern: "*.{txt,tsv}"


output:
  - emx:
        type: file
        description: A gene expression matrix in binary format.
        pattern: "*.{emx}"
  - version:
        type: file
        description: File containing software versions
        pattern: "version.txt"

authors:
  - "@spficklin", "@bentsherman"
