contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #kinc channel"
    url: https://nfcore.slack.com/channels/kinc
    about: Discussion about the systemsgenetics/kinc-nf pipeline
